# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Wilka Carvalho
tagline:             'Reinforcement Learning Research & Cognitive Scientist'
description:         ''
url:                 https://wcarvalho.github.io/
baseurl:             ''
markdown:            kramdown
highlighter:         rouge



# markdown:            redcarpet

# About/contact
author:
  name:              Wilka Carvalho
  url:               https://wcarvalho.github.io/
  email:             wcarvalho92@gmail.com

# Custom vars
version:             1.0.0

#Disqus
disqus_shortname: wilkacarvalho

# Gems
plugins: 
  - jekyll-sitemap
  - jekyll-scholar
  # - jekyll-related-posts

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile

