name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - source

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build & Deploy to GitHub Pages
        uses: joshlarsen/jekyll4-deploy-gh-pages@master
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}

      # - uses: helaili/jekyll-action@v2
      #   with:
      #     token: ${{secrets.GITHUB_TOKEN}}
      #     target_branch: 'gh-pages'

      # - name: Build Jekyll site
      #   run: |
      #     set -xo pipefail
      #     rm -rf _site/*
      #     gem install bundler
      #     bundle install
      #     bundle exec jekyll build
      #     cp CNAME _site/CNAME

      # - name: Deploy
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   run: |
      #     set -xo pipefail
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git checkout master
      #     ls -Q | grep -v _site | xargs rm -rf
      #     mv _site/* .
      #     rm -rf _site
      #     rm -rf .jekyll-cache
      #     [[ -n "$(git status --porcelain)" ]] || exit 0
      #     git add .
      #     git commit -m "Build $(git rev-parse source | grep -o '^.\{10\}')"
      #     git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" master